import {AtwColumnDef} from "@atw/components";

export type Axe = {
    id: number,
    brokerTicker: string,
    axeType: string,
    axeId: number,
    touchCount: number,
    scope: string,
    status: string,
    secIdType: string,
    secId: string,
    aladdinId: string,
    tranType: string,
    actualSize: number,
    source: string,
    brokerCode: string,
    priceCurrency: string,
    priceType: string,
    price: number,
    benchId: string,
    benchIdType: string,
    benchAladdinId: string,
    submittedBy: string,
    effectiveTime: Date,
    modifiedBy: string,
    modifiedTime: Date,
    naturalFlag: string,
    expiryType: string,
    expiryTime: Date,
    createdBy: string,
    createdTime: Date,
    ecnAxeId: string,
}

const base: AtwColumnDef<Axe> = {
    field: "price",
    type: "string",
    label: "Auto",
    minWidth: 0,
    width: 150,
    preferredWidth: 150,
    sortable: true,
    sort: [],
    resizable: true
};

export const AXE_COLUMNS: AtwColumnDef<Axe>[] = [
    {...base, width: 125, type: "string", field: "brokerTicker", label: "Broker Ticker"},
    {...base, width: 150, type: "string", field: "axeType", label: "Axe Type"},
    {...base, width: 125, type: "string", field: "axeId", label: "Axe Id"},
    {...base, width: 150, type: "number", field: "touchCount", label: "Touch Count"},
    {...base, width: 150, type: "string", field: "scope", label: "Scope"},
    {...base, width: 75, type: "string", field: "status", label: "Status"},
    {...base, width: 150, type: "string", field: "secIdType", label: "Sec Id Type"},
    {...base, width: 150, type: "string", field: "secId", label: "Sec Id"},
    {...base, width: 150, type: "string", field: "aladdinId", label: "Aladdin Id"},
    {...base, width: 150, type: "string", field: "tranType", label: "Tran Type"},
    {...base, width: 150, type: "quantity", field: "actualSize", label: "Actual Size"},
    {...base, width: 150, type: "string", field: "source", label: "Source"},
    {...base, width: 150, type: "string", field: "brokerCode", label: "Broker Code"},
    {...base, width: 150, type: "string", field: "priceCurrency", label: "Price Currency"},
    {...base, width: 100, type: "string", field: "priceType", label: "Price Type"},
    {...base, width: 100, type: "price", field: "price", label: "Price", className: "number"},
    {...base, width: 150, type: "string", field: "benchId", label: "Bench Id"},
    {...base, width: 150, type: "string", field: "benchIdType", label: "Bench Id Type"},
    {...base, width: 150, type: "string", field: "benchAladdinId", label: "Bench Aladdin Id"},
    {...base, width: 150, type: "string", field: "submittedBy", label: "Submitted By"},
    {...base, width: 100, type: "date", field: "effectiveTime", label: "Effective Date"},
    {...base, width: 100, type: "time", field: "effectiveTime", label: "Effective Time"},
    {...base, width: 150, type: "string", field: "modifiedBy", label: "Modified By"},
    {...base, width: 100, type: "date", field: "modifiedTime", label: "Modified Date"},
    {...base, width: 100, type: "time", field: "modifiedTime", label: "Modified Time"},
    {...base, width: 150, type: "string", field: "naturalFlag", label: "Natural Flag"},
    {...base, width: 150, type: "string", field: "expiryType", label: "Expiry Type"},
    {...base, width: 100, type: "date", field: "expiryTime", label: "Expiry Date"},
    {...base, width: 100, type: "time", field: "expiryTime", label: "Expiry Time"},
    {...base, width: 150, type: "string", field: "createdBy", label: "Created By"},
    {...base, width: 100, type: "date", field: "createdTime", label: "Created Date"},
    {...base, width: 100, type: "time", field: "createdTime", label: "Created Time"},
    {...base, width: 150, type: "string", field: "ecnAxeId", label: "ECN Axe Id"}
];
